'use strict';

export const CREATE_NEW_ACCOUNT_PROCESSING = 'CREATE_NEW_ACCOUNT_PROCESSING';
export const CREATE_NEW_ACCOUNT_DONE = 'CREATE_NEW_ACCOUNT_DONE';
export const CREATE_NEW_ACCOUNT_ERROR = 'CREATE_NEW_ACCOUNT_ERROR';
export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
